# Generated by Django 5.0.3 on 2024-12-30 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobportalApp', '0004_job_delete_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(null=True, upload_to='')),
                ('applydate', models.DateField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobportalApp.job')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobportalApp.studentuser')),
            ],
        ),
        migrations.DeleteModel(
            name='Applicant',
        ),
    ]
